version: "3.8"
services:
  prometheus:
    image: quay.io/prometheus/prometheus
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"

  snmp-exporter:
    image: quay.io/prometheus/snmp-exporter
    container_name: snmp-exporter
    restart: unless-stopped
    volumes:
      - ./snmp-exporter:/etc/snmp-exporter/
    ports:
      - "9116:9116"

volumes:
  prometheus-data: {}
  grafana-data: {}
